### ISSUE TITLE
Story.update() disallowed-keys

### ISSUE THREAD

**Issue by philipesteiff** [humberaquino/exclubhouse#4]
Hey 👋 

I've found a bug when using `Story.update() /2`, I'm receiving `status 400` because some invalid parameters in the body. 

The api documentation doesn't allow some keys that are defined on `Input.Story{}` as:
- `external_tickets` 
- `story_links`
- `tasks`

https://clubhouse.io/api/rest/v3/#URL-Parameters-45270

**Comment by humberaquino** [comment]
🏆
